language: php

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.4"

services:
  - mysql
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.0
 - 7.1

env:
 global:
  - MOODLE_BRANCH=MOODLE_32_STABLE
  - MOODLE_REPO=git://github.com/procudin/moodle.git
  - IGNORE_NAMES=fa_comparison_test.php,fa_tags_equivalence_test.php
  - PHPUNIT_IGNORE_PATHS=$IGNORE_NAMES
 matrix:
  - DB=pgsql 
  
before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - sudo apt-get install graphviz
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
  - moodle-plugin-ci add-config '$CFG->pathtodot = "dot";'
  - moodle-plugin-ci add-config '$CFG->qtype_writregex_groups_pairs_limit = 10000;'

script:
#  - moodle-plugin-ci phplint
#  - moodle-plugin-ci phpcpd
#  - moodle-plugin-ci phpmd
#  - moodle-plugin-ci codechecker
#  - moodle-plugin-ci validate
#  - moodle-plugin-ci savepoints
#  - moodle-plugin-ci mustache
#  - moodle-plugin-ci grunt
#  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat
